import type { Metadata } from "next";
import StoreProvider from "./StoreProvider";
import recipesData from "../mocks/recipes.json";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <StoreProvider recipes={recipesData}>
      <html lang="en">
        <body style={{ margin: 0 }}>{children}</body>
      </html>
    </StoreProvider>
  );
}
